{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spiffe-step-ssh.serviceAccountName" . }}-config
  labels:
    {{- include "spiffe-step-ssh.labels" . | nindent 4 }}
    component: config
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
