{{- $root := . }}
{{- if or (ne .Values.keyManager.awsKMS.accessKeyID "") (ne .Values.keyManager.awsKMS.secretAccessKey "") (ne .Values.secrets.aws.accessKeyID "") (ne .Values.secrets.aws.secretAccessKey "") (ne .Values.secrets. gcp.applicationCredentials "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.fullname" $root }}-cloud
  namespace: {{ include "spire-server.namespace" $root }}
data:
  {{- if ne .Values.keyManager.awsKMS.accessKeyID "" }}
  AWS_KMS_ACCESS_KEY_ID: {{ .Values.keyManager.awsKMS.accessKeyID | b64enc }}
  {{- end }}
  {{- if ne .Values.keyManager.awsKMS.secretAccessKey "" }}
  AWS_KMS_SECRET_ACCESS_KEY: {{ .Values.keyManager.awsKMS.secretAccessKey | b64enc }}
  {{- end }}
  {{- if ne .Values.secrets.aws.accessKeyID "" }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyID | b64enc }}
  {{- end }}
  {{- if ne .Values.secrets.aws.secretAccessKey "" }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | b64enc }}
  {{- end }}
  {{- if ne .Values.secrets.gcp.applicationCredentials "" }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.secrets.gcp.applicationCredentials | b64enc }}
  {{- end }}
{{- end }}
