apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-step-ssh.fullname" . }}-fetchca
  labels:
    {{- include "spire-step-ssh.labels" . | nindent 4 }}
data:
  spiffe-helper-init.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cmd = ""
    cmd_args = ""
    cert_dir = "/certs"
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "ca.pem"
    add_intermediates_to_bundle = true
  spiffe-helper-sidecar.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cmd = "/busybox/busybox"
    cmd_args = "sh /update.sh"
    cert_dir = "/certs"
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "ca.pem"
    add_intermediates_to_bundle = true
  update.sh: |
    #!/bin/sh
    /busybox/busybox kill -HUP `/busybox/busybox busybox cat /pid/pid`
