apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-step-ssh.fullname" . }}-certs
  labels:
    {{- include "spire-step-ssh.labels" . | nindent 4 }}
data:
  "root_ca.crt": |
    {{- .Values.inject.certificates.root_ca | nindent 4}}
  "intermediate_ca.crt": |
    {{ .Values.inject.certificates.intermediate_ca | nindent 4}}
  "ssh_host_ca_key.pub": |
    {{ .Values.inject.certificates.ssh_host_ca | nindent 4 }}
  "ssh_user_ca_key.pub": |
    {{ .Values.inject.certificates.ssh_user_ca | nindent 4 }}
