apiVersion: v2
name: spike-keeper
description: A Helm chart to deploy SPIKE Keeper
type: application
version: 0.1.0
appVersion: "v0.4.1"
home: https://github.com/spiffe/helm-charts-hardened/tree/main/charts/spire
sources:
  - https://github.com/spiffe/spike
icon: https://spike.ist/assets/spike-banner.png
maintainers:
  - name: kfox1111
    email: Kevin.Fox@pnnl.gov
