global:
  spire:
    clusterName: production
    trustDomain: production.other

spire-server:
  ca_subject:
    country: US
    organization: Production
    common_name: production.other

#  ingress:
#    host: spire-server
#  federation:
#     ingress:
#       host: spire-server-federation
#       tlsSecret: tls-cert

# spiffe-oidc-discovery-provider:
#   ingress:
#     host: oidc-discovery
#     tlsSecret: tls-cert

tornjak-frontend:
  apiServerURL: https://tornjak-backend.production.other/

